on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

name: CI
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        cache: [use-cache, no-cache]
        restore: [cache-restored, no-cache-restored]
        exclude:
          - arch: aarch64
            cache: no-cache
          - arch: aarch64
            restore: no-cache-restored
          - cache: no-cache
            restore: cache-restored
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Set up docker
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          curl https://download.docker.com/linux/static/stable/x86_64/docker-27.3.1.tgz --output docker.tgz
          tar xzvf docker.tgz
          chmod -R +x docker
          mv docker/* /usr/bin
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
        with:
          platforms: arm64
      - uses: ./flatpak-builder
        with:
          bundle: org.example.MyApp.Devel-${{ matrix.cache }}-${{ matrix.restore }}.flatpak
          manifest-path: ./flatpak-builder/tests/test-project/org.example.MyApp.yaml
          cache: ${{ matrix.cache == 'use-cache' }}
          restore-cache: ${{ matrix.restore == 'cache-restored' }}
          cache-key: flatpak-builder-${{ github.sha }}-${{ matrix.restore }}
          arch: ${{ matrix.arch }}
          verbose: true
      # TODO: setup a flat-manager before and use it later here
      #- uses: ./flat-manager
      #  with:
      #    repository: elementary
      #    flat-manager-url: https://flatpak-api.elementary.io
      #    token: some_very_hidden_token

  flatpak-builder-stop-at:
    name: Flatpak Builder Stop At
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: ./flatpak-builder
        with:
          manifest-path: ./flatpak-builder/tests/test-project/org.example.MyApp.yaml
          stop-at-module: testproject
          cache: false
          verbose: true

  flatpak-builder-cache-hit:
    name: Flatpak Builder Cache Hit
    runs-on: ubuntu-latest
    needs: flatpak-builder
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: ./flatpak-builder
        with:
          bundle: org.example.MyApp.Devel-cache-hit.flatpak
          manifest-path: ./flatpak-builder/tests/test-project/org.example.MyApp.yaml
          cache-key: flatpak-builder-${{ github.sha }}-no-cache-restored
          verbose: true

  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        # 4.2.0
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --also=dev
        working-directory: flatpak-builder
      - run: yarn test
        working-directory: flatpak-builder

  eslint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Use Node.js 22
        # 4.2.0
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with:
          node-version: "22"
      - run: yarn install --also=dev
        working-directory: flatpak-builder
      - run: yarn run eslint .
        working-directory: flatpak-builder
      - run: yarn install --also=dev
        working-directory: flat-manager
      - run: yarn run eslint .
        working-directory: flat-manager
